name: Slack_Github_Action

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Sending notification on Slack using Webhooks
        uses: 8398a7/action-slack@v3
        with:
          payload: |
            {
             "text": ""
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
          
