name: Slack_Github_Action

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Sending notification on Slack using Webhooks
        uses: 8398a7/action-slack@v4.2.0
        with:
          status: custom
          custom_payload: |
            {
              "text": "Hello, World!"
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
